version: '3.7'

services:
  frontend:
    build: .
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - '.:/home/frontend/frontend'
      - '/home/frontend/frontend/node_modules'
    ports:
      - "9090:9090"
    tty: true
